### ISSUE TITLE
How to flash firmware to router ?

### ISSUE THREAD

**Issue by irisvn** [yuos-bit/Padavan#3]
Hello @yuos-bit , 

I using Xiaomi Router MI-4C, OpenWRT. 
I wanna flash padavan. How to flash padavan to my router ?

Thanks, :D

**Comment by yuos-bit** [comment]
hello.dear
You can use breed to update my firmware to your needs

**Comment by irisvn** [comment]
> hello.dear
> You can use breed to update my firmware to your needs

Hi, 

I don't understand this picture:

[http://s1.ax1x.com/2020/09/09/w8D6Xj.png](http://s1.ax1x.com/2020/09/09/w8D6Xj.png)

What is "config" ???

Sorry, I don't understand Chinese. :D

 Thanks,

**Comment by Tinyu-Zhao** [comment]
想问下在为小米4C烧录时需要像烧录Openwrt一样在环境变量里设置autoboot.command = boot flash 0x160000吗
