### ISSUE TITLE
Questions about Ruijie firmware

### ISSUE THREAD

**Issue by Zlylanyun** [yuos-bit/Padavan#4]
Hello developer, when I use your Xiaomi router 4c with Ruijie certified firmware, the log in Mentohust shows that the user owes fees, but in fact there is no. The same is true if you choose the campus network when using the client, but choose Unicom Wait for the operator, I don’t see the option to select the operator in Mentohust. Mpf file and I don’t know how to use it.

**Comment by yuos-bit** [comment]
关于锐捷的问题你可以试试新插件叫做mineap
