### ISSUE TITLE
MI-4A-100M 编译成功，开机一直重启

### ISSUE THREAD

**Issue by byludy** [yuos-bit/Padavan#5]
用的是你的配置，编译后用breed刷进去
不同的是为了实现在线编译，修改了 kernel-3.4.x.config 文件
增加下面3行
```
CONFIG_NF_CONNTRACK_CHAIN_EVENTS=y
# CONFIG_RT_SECOND_IF_MT7915 is not set
# CONFIG_RT_THIRD_IF_MT7915 is not set
```

可以看看https://github.com/byludy/Padavan-MI-4A-100M
里面有编译好的固件

**Comment by yuos-bit** [comment]
嗯，可能移植有些问题，后面再修改吧。最近太忙了

**Comment by byludy** [comment]
不知道是不是我的路由问题
我刷别人编译的padavan也是开不了机   只有刷openwrt能开机
是不是要清配置啊    小米 4a 100m 要怎么在breed里面清配置

**Comment by yuos-bit** [comment]
> 不知道是不是我的路由问题
> 我刷别人编译的padavan也是开不了机   只有刷openwrt能开机
> 是不是要清配置啊    小米 4a 100m 要怎么在breed里面清配置

这个不是很清楚，因为我这边没有小米路由，4a百兆的这个实体机器没办法做测试，我这边只有千兆的机器，所以我这边后面可能也会去适配一下千兆的路由器。

**Comment by yuos-bit** [comment]
> 不知道是不是我的路由问题
> 我刷别人编译的padavan也是开不了机   只有刷openwrt能开机
> 是不是要清配置啊    小米 4a 100m 要怎么在breed里面清配置

基本上都是别人给我寄路由器，然后我才会去试配，然后或者是我看到他们那个无线芯片一样的话就顺手做一下适配，但是那种都是为测试的，所以也不确定能不能用。然后一般我会找个群友帮我做测试，然后他测试正常我就会公布这个配置。
至少当时他测试的时候是正常的。

**Comment by yuos-bit** [comment]
你好，小米4A百兆版的问题已修复，顺便新增了小米路由4A千兆版的固件，你可以看下
