### ISSUE TITLE
无法添加zerotier

### ISSUE THREAD

**Issue by ixinshang** [yuos-bit/Padavan#9]
你好，作者。
使用actions编译添加zerotier，编译报错。
`
echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=y" >> .config #zerotier ~1.3M
`
```
/opt/rt-n56u/trunk/../toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-g++ -mips32r2 -march=mips32r2 -mtune=1004kc -Os -fomit-frame-pointer -pipe  -Dlinux -D__linux__ -Dunix -DEMBED -I/opt/rt-n56u/trunk/stage/include -Wall -Wno-trigraphs -Wno-strict-aliasing -Wno-format-security -fno-tree-slsr -fno-aggressive-loop-optimizations  -Wall -Wno-deprecated -std=c++17 -pthread -Izeroidc/target -isystem ext -DNDEBUG  -DZT_USE_MINIUPNPC -DMINIUPNP_STATICLIB -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DOS_STRING="\"Linux\"" -DMINIUPNPC_VERSION_STRING="\"2.0\"" -DUPNP_VERSION_STRING="\"UPnP/1.1\"" -DENABLE_STRNATPMPERR -DZT_NO_TYPE_PUNNING -DZT_BUILD_PLATFORM=1 -DZT_BUILD_ARCHITECTURE=5 -DZT_SOFTWARE_UPDATE_DEFAULT="\"disable\"" -D_MT_ALLOCATOR_H -D_POOL_ALLOCATOR_H -D_EXTPTR_ALLOCATOR_H -D_DEBUG_ALLOCATOR_H -fPIC -fPIE   -c -o osdep/PortMapper.o osdep/PortMapper.cpp
make[3]: *** [<builtin>: service/OneService.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/opt/rt-n56u/trunk/user/zerotier/ZeroTierOne-1.10.2'
make[2]: Leaving directory '/opt/rt-n56u/trunk/user/zerotier'
make[2]: *** [Makefile:8: all] Error 2
make[1]: *** [Makefile:257: all] Error 2
make: *** [Makefile:202: user_only] Error 2
make[1]: Leaving directory '/opt/rt-n56u/trunk/user'
Error: Process completed with exit code 2.
```

这部分确实没看懂，请指教。

**Comment by ixinshang** [comment]
> 你好，经过测试，问题已复现。 https://github.com/yuos-bit/Padavan-build/actions/runs/3780995680/jobs/6427526949 经过检查，是源码缺失所致，且zerotier版本过低，目前已升级最新且测试云编译通过。 测试流程详见： https://github.com/yuos-bit/Padavan-build/actions/runs/3781350601

@yuos-bit 我反馈的时候忘记反馈设备型号了。 我测试的R3G。 目前复制了最新的R3G的yml，测试依旧报错。
```
make[3]: *** [<builtin>: service/OneService.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/opt/rt-n56u/trunk/user/zerotier/ZeroTierOne-1.10.2'
make[2]: Leaving directory '/opt/rt-n56u/trunk/user/zerotier'
make[1]: Leaving directory '/opt/rt-n56u/trunk/user'
make[2]: *** [Makefile:8: all] Error 2
make[1]: *** [Makefile:257: all] Error 2
make: *** [Makefile:202: user_only] Error 2
Error: Process completed with exit code 2.
```

**Comment by yuos-bit** [comment]
你可以指定版本为ZeroTierOne-1.8.4然后再试试


864529498
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuos-bit/Padavan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月26日(星期一) 晚上11:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuos-bit/Padavan] 无法添加zerotier (Issue #9)





  
你好，经过测试，问题已复现。 https://github.com/yuos-bit/Padavan-build/actions/runs/3780995680/jobs/6427526949 经过检查，是源码缺失所致，且zerotier版本过低，目前已升级最新且测试云编译通过。 测试流程详见： https://github.com/yuos-bit/Padavan-build/actions/runs/3781350601
  
@yuos-bit 我反馈的时候忘记反馈设备型号了。 我测试的R3G。 目前复制了最新的R3G的yml，测试依旧报错。
 make[3]: *** [<builtin&gt;: service/OneService.o] Error 1 make[3]: *** Waiting for unfinished jobs.... make[3]: Leaving directory '/opt/rt-n56u/trunk/user/zerotier/ZeroTierOne-1.10.2' make[2]: Leaving directory '/opt/rt-n56u/trunk/user/zerotier' make[1]: Leaving directory '/opt/rt-n56u/trunk/user' make[2]: *** [Makefile:8: all] Error 2 make[1]: *** [Makefile:257: all] Error 2 make: *** [Makefile:202: user_only] Error 2 Error: Process completed with exit code 2.

**Comment by ixinshang** [comment]
> 你可以指定版本为ZeroTierOne-1.8.4然后再试试 864529498 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yuos-bit/Padavan" ***@***.***&gt;; 发送时间:&nbsp;2022年12月26日(星期一) 晚上11:32 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [yuos-bit/Padavan] 无法添加zerotier (Issue #9) 你好，经过测试，问题已复现。 https://github.com/yuos-bit/Padavan-build/actions/runs/3780995680/jobs/6427526949 经过检查，是源码缺失所致，且zerotier版本过低，目前已升级最新且测试云编译通过。 测试流程详见： https://github.com/yuos-bit/Padavan-build/actions/runs/3781350601 @yuos-bit 我反馈的时候忘记反馈设备型号了。 我测试的R3G。 目前复制了最新的R3G的yml，测试依旧报错。 make[3]: *** [<builtin&gt;: service/OneService.o] Error 1 make[3]: *** Waiting for unfinished jobs.... make[3]: Leaving directory '/opt/rt-n56u/trunk/user/zerotier/ZeroTierOne-1.10.2' make[2]: Leaving directory '/opt/rt-n56u/trunk/user/zerotier' make[1]: Leaving directory '/opt/rt-n56u/trunk/user' make[2]: *** [Makefile:8: all] Error 2 make[1]: *** [Makefile:257: all] Error 2 make: *** [Makefile:202: user_only] Error 2 Error: Process completed with exit code 2. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

我看到你也在测试。  等会儿看看测试结果。
感谢大半夜排查问题

**Comment by yuos-bit** [comment]
https://github.com/zerotier/ZeroTierOne/issues/1582



使用1.10.2问题复现后我已设置回退到1.8.4，你可以尝试编译，等我有空的时候修改1.10.2的源码后再重新更新吧




864529498
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuos-bit/Padavan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月26日(星期一) 晚上11:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuos-bit/Padavan] 无法添加zerotier (Issue #9)





  
你可以指定版本为ZeroTierOne-1.8.4然后再试试 864529498 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yuos-bit/Padavan" @.&gt;; 发送时间:&nbsp;2022年12月26日(星期一) 晚上11:32 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [yuos-bit/Padavan] 无法添加zerotier (Issue #9) 你好，经过测试，问题已复现。 https://github.com/yuos-bit/Padavan-build/actions/runs/3780995680/jobs/6427526949 经过检查，是源码缺失所致，且zerotier版本过低，目前已升级最新且测试云编译通过。 测试流程详见： https://github.com/yuos-bit/Padavan-build/actions/runs/3781350601 @yuos-bit 我反馈的时候忘记反馈设备型号了。 我测试的R3G。 目前复制了最新的R3G的yml，测试依旧报错。 make[3]: *** [<builtin&gt;: service/OneService.o] Error 1 make[3]: *** Waiting for unfinished jobs.... make[3]: Leaving directory '/opt/rt-n56u/trunk/user/zerotier/ZeroTierOne-1.10.2' make[2]: Leaving directory '/opt/rt-n56u/trunk/user/zerotier' make[1]: Leaving directory '/opt/rt-n56u/trunk/user' make[2]: *** [Makefile:8: all] Error 2 make[1]: *** [Makefile:257: all] Error 2 make: *** [Makefile:202: user_only] Error 2 Error: Process completed with exit code 2. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
我看到你也在测试。  等会儿看看测试结果。
 感谢大半夜排查问题

**Comment by ixinshang** [comment]
> [zerotier/ZeroTierOne#1582](https://github.com/zerotier/ZeroTierOne/issues/1582) 使用1.10.2问题复现后我已设置回退到1.8.4，你可以尝试编译，等我有空的时候修改1.10.2的源码后再重新更新吧 864529498 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yuos-bit/Padavan" ***@***.***&gt;; 发送时间:&nbsp;2022年12月26日(星期一) 晚上11:51 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [yuos-bit/Padavan] 无法添加zerotier (Issue #9) 你可以指定版本为ZeroTierOne-1.8.4然后再试试 864529498 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yuos-bit/Padavan" @.&gt;; 发送时间:&nbsp;2022年12月26日(星期一) 晚上11:32 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [yuos-bit/Padavan] 无法添加zerotier (Issue #9) 你好，经过测试，问题已复现。 https://github.com/yuos-bit/Padavan-build/actions/runs/3780995680/jobs/6427526949 经过检查，是源码缺失所致，且zerotier版本过低，目前已升级最新且测试云编译通过。 测试流程详见： https://github.com/yuos-bit/Padavan-build/actions/runs/3781350601 @yuos-bit 我反馈的时候忘记反馈设备型号了。 我测试的R3G。 目前复制了最新的R3G的yml，测试依旧报错。 make[3]: *** [<builtin&gt;: service/OneService.o] Error 1 make[3]: *** Waiting for unfinished jobs.... make[3]: Leaving directory '/opt/rt-n56u/trunk/user/zerotier/ZeroTierOne-1.10.2' make[2]: Leaving directory '/opt/rt-n56u/trunk/user/zerotier' make[1]: Leaving directory '/opt/rt-n56u/trunk/user' make[2]: *** [Makefile:8: all] Error 2 make[1]: *** [Makefile:257: all] Error 2 make: *** [Makefile:202: user_only] Error 2 Error: Process completed with exit code 2. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt; 我看到你也在测试。 等会儿看看测试结果。 感谢大半夜排查问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

我看到你又在测试了，等下看看结果。

个人对padavan的插件的操作还不太熟悉。。

**Comment by ixinshang** [comment]
> [zerotier/ZeroTierOne#1582](https://github.com/zerotier/ZeroTierOne/issues/1582) 使用1.10.2问题复现后我已设置回退到1.8.4，你可以尝试编译，等我有空的时候修改1.10.2的源码后再重新更新吧 864529498 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yuos-bit/Padavan" ***@***.***&gt;; 发送时间:&nbsp;2022年12月26日(星期一) 晚上11:51 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [yuos-bit/Padavan] 无法添加zerotier (Issue #9) 你可以指定版本为ZeroTierOne-1.8.4然后再试试 864529498 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yuos-bit/Padavan" @.&gt;; 发送时间:&nbsp;2022年12月26日(星期一) 晚上11:32 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [yuos-bit/Padavan] 无法添加zerotier (Issue #9) 你好，经过测试，问题已复现。 https://github.com/yuos-bit/Padavan-build/actions/runs/3780995680/jobs/6427526949 经过检查，是源码缺失所致，且zerotier版本过低，目前已升级最新且测试云编译通过。 测试流程详见： https://github.com/yuos-bit/Padavan-build/actions/runs/3781350601 @yuos-bit 我反馈的时候忘记反馈设备型号了。 我测试的R3G。 目前复制了最新的R3G的yml，测试依旧报错。 make[3]: *** [<builtin&gt;: service/OneService.o] Error 1 make[3]: *** Waiting for unfinished jobs.... make[3]: Leaving directory '/opt/rt-n56u/trunk/user/zerotier/ZeroTierOne-1.10.2' make[2]: Leaving directory '/opt/rt-n56u/trunk/user/zerotier' make[1]: Leaving directory '/opt/rt-n56u/trunk/user' make[2]: *** [Makefile:8: all] Error 2 make[1]: *** [Makefile:257: all] Error 2 make: *** [Makefile:202: user_only] Error 2 Error: Process completed with exit code 2. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt; 我看到你也在测试。 等会儿看看测试结果。 感谢大半夜排查问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

我看最新的编译成功了
